apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  namespace: stateful-app-demo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: canary-app
        image: ghcr.io/anastasiia-gubska/canarydemo/app:v2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: DB_URL
          value: "postgres://postgres:postgres@postgres:5432/testdb?sslmode=disable"
  strategy:
    canary:
      stableService: canary-demo-stable
      canaryService: canary-demo-canary
      steps:
      - setWeight: 25        # Send 25% of traffic to v2
      - pause: {}            # Wait for manual approval (kubectl argo rollouts promote)
      - setWeight: 50        # Send 50% of traffic to v2
      - pause: {} 
      - setWeight: 100
      - pause: {}

---
# STABLE SERVICE (Points to the current "Live" version)
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-stable
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: canary-demo
---
# CANARY SERVICE (Points to the "New" version being tested)
apiVersion: v1
kind: Service
metadata:
  name: canary-demo-canary
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: canary-demo